# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1280, 720)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.control_panel = QtWidgets.QFrame(self.central_widget)
        self.control_panel.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.control_panel.setFrameShape(QtWidgets.QFrame.Panel)
        self.control_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_panel.setLineWidth(2)
        self.control_panel.setMidLineWidth(2)
        self.control_panel.setObjectName("control_panel")
        self.gridLayout = QtWidgets.QGridLayout(self.control_panel)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(7, 7, 7, 7)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.num_piece_label = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.num_piece_label.setFont(font)
        self.num_piece_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.num_piece_label.setLineWidth(0)
        self.num_piece_label.setObjectName("num_piece_label")
        self.horizontalLayout_2.addWidget(self.num_piece_label)
        self.num_piece = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.num_piece.setFont(font)
        self.num_piece.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 66, 66);")
        self.num_piece.setFrameShape(QtWidgets.QFrame.Panel)
        self.num_piece.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.num_piece.setLineWidth(2)
        self.num_piece.setMidLineWidth(2)
        self.num_piece.setText("")
        self.num_piece.setAlignment(QtCore.Qt.AlignCenter)
        self.num_piece.setObjectName("num_piece")
        self.horizontalLayout_2.addWidget(self.num_piece)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.monitoring_dir_label = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.monitoring_dir_label.setFont(font)
        self.monitoring_dir_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.monitoring_dir_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.monitoring_dir_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.monitoring_dir_label.setLineWidth(1)
        self.monitoring_dir_label.setMidLineWidth(0)
        self.monitoring_dir_label.setScaledContents(False)
        self.monitoring_dir_label.setObjectName("monitoring_dir_label")
        self.gridLayout.addWidget(self.monitoring_dir_label, 1, 0, 1, 1)
        self.dir_path = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dir_path.setFont(font)
        self.dir_path.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 66, 66);")
        self.dir_path.setFrameShape(QtWidgets.QFrame.Panel)
        self.dir_path.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dir_path.setLineWidth(2)
        self.dir_path.setMidLineWidth(2)
        self.dir_path.setText("")
        self.dir_path.setObjectName("dir_path")
        self.gridLayout.addWidget(self.dir_path, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reference = QtWidgets.QPushButton(self.control_panel)
        self.reference.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.reference.setFont(font)
        self.reference.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reference.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 66, 66);")
        self.reference.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/reference.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reference.setIcon(icon)
        self.reference.setIconSize(QtCore.QSize(30, 30))
        self.reference.setAutoDefault(False)
        self.reference.setDefault(False)
        self.reference.setFlat(False)
        self.reference.setObjectName("reference")
        self.horizontalLayout_4.addWidget(self.reference)
        self.play = QtWidgets.QPushButton(self.control_panel)
        self.play.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.play.setFont(font)
        self.play.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 66, 66);")
        self.play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon1)
        self.play.setIconSize(QtCore.QSize(30, 30))
        self.play.setCheckable(False)
        self.play.setDefault(True)
        self.play.setObjectName("play")
        self.monitoring_control = QtWidgets.QButtonGroup(main_window)
        self.monitoring_control.setObjectName("monitoring_control")
        self.monitoring_control.addButton(self.play)
        self.horizontalLayout_4.addWidget(self.play)
        self.stop = QtWidgets.QPushButton(self.control_panel)
        self.stop.setMaximumSize(QtCore.QSize(40, 16777215))
        self.stop.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 66, 66);")
        self.stop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon2)
        self.stop.setIconSize(QtCore.QSize(30, 30))
        self.stop.setObjectName("stop")
        self.monitoring_control.addButton(self.stop)
        self.horizontalLayout_4.addWidget(self.stop)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.filename_label = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.filename_label.setFont(font)
        self.filename_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.filename_label.setLineWidth(0)
        self.filename_label.setObjectName("filename_label")
        self.horizontalLayout_3.addWidget(self.filename_label)
        self.problem_list = QtWidgets.QComboBox(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.problem_list.setFont(font)
        self.problem_list.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 66, 66);")
        self.problem_list.setFrame(True)
        self.problem_list.setObjectName("problem_list")
        self.horizontalLayout_3.addWidget(self.problem_list)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.export = QtWidgets.QPushButton(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.export.setFont(font)
        self.export.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 66, 66);")
        self.export.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export.setIcon(icon3)
        self.export.setIconSize(QtCore.QSize(30, 30))
        self.export.setObjectName("export")
        self.gridLayout.addWidget(self.export, 4, 1, 1, 1)
        self.open_file = QtWidgets.QPushButton(self.control_panel)
        self.open_file.setMaximumSize(QtCore.QSize(40, 16777215))
        self.open_file.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 66, 66);")
        self.open_file.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file.setIcon(icon4)
        self.open_file.setIconSize(QtCore.QSize(30, 30))
        self.open_file.setObjectName("open_file")
        self.gridLayout.addWidget(self.open_file, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.control_panel)
        self.frame_view = FrameWidget(self.central_widget)
        self.frame_view.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.frame_view.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view.setLineWidth(2)
        self.frame_view.setMidLineWidth(2)
        self.frame_view.setObjectName("frame_view")
        self.verticalLayout_2.addWidget(self.frame_view)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.piece_view = QtWidgets.QListWidget(self.central_widget)
        self.piece_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.piece_view.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.piece_view.setFrameShape(QtWidgets.QFrame.Panel)
        self.piece_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.piece_view.setLineWidth(2)
        self.piece_view.setMidLineWidth(2)
        self.piece_view.setAutoScrollMargin(16)
        self.piece_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.piece_view.setProperty("showDropIndicator", False)
        self.piece_view.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.piece_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.piece_view.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.piece_view.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.piece_view.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.piece_view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.piece_view.setMovement(QtWidgets.QListView.Static)
        self.piece_view.setFlow(QtWidgets.QListView.TopToBottom)
        self.piece_view.setProperty("isWrapping", False)
        self.piece_view.setResizeMode(QtWidgets.QListView.Adjust)
        self.piece_view.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.piece_view.setViewMode(QtWidgets.QListView.ListMode)
        self.piece_view.setModelColumn(0)
        self.piece_view.setUniformItemSizes(False)
        self.piece_view.setObjectName("piece_view")
        self.verticalLayout.addWidget(self.piece_view)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        main_window.setCentralWidget(self.central_widget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Viewer"))
        self.num_piece_label.setText(_translate("main_window", "number of piece"))
        self.monitoring_dir_label.setText(_translate("main_window", "monitoring directory"))
        self.filename_label.setText(_translate("main_window", "filename"))

from widgets import FrameWidget
import viewer_rc
