version: 2
jobs:
  build:
    docker:
      - image: namachan10777/procon:develop
    working_directory: /ci
    steps:
      - checkout
      - run:
          name: namachan_solver
          command: ./solver/namachan/test.sh
      - run:
          name: format
          command: ./format/test.sh
