version: 2
jobs:
  build:
    docker:
      - image: namachan10777/procon:develop
    working_directory: /ci
    steps:
      - run:
          name: namachan_solver
          command: dub test --root=./solver/namachan/