version: 2
jobs:
  build:
    docker:
      - image: namachan10777/procon:develop
    working_directory: /ci
    steps:
      - checkout
      - run:
          name: namachan_solver
          command: bash ./solver/namachan/test.sh
      - run:
          name: pyencoder
          command: bash ./tools/pyencoder/test.sh
